char *test_initialize_layer(void);
char *test_initialize_first_layer(void);
char *test_apply_transformation(void);
char *test_apply_softmax_nondestructive(void);
char *test_apply_activation_sigmoid(void);
char *test_apply_activation_relu(void);
char *test_apply_activation_softmax(void);
void basic_perceptron_suite(int *failures);
char *test_build_network(void);
char *test_feed_forward(void);